config/routes.rb
SampleApp::Application.routes.draw do
    
    resources :users

    match '/signup', :to => 'users#new'

    match '/home', :to => 'pages#home'

    match '/contact', :to => 'pages#contact'

    match '/about', :to => 'pages#about'

    match '/help', :to => 'pages#help'

    root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :nom, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save :encrypt_password

  validates :nom, :presence => true,
  				  :length => { :maximum => 50 }
  validates :email, :presence => true,
  					:format => { :with => email_regex },
  					:uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
  					   :confirmation => true,
  					   :length => { :within => 6..40 }
    
  def has_password?(password_send)
    self.encrypted_password == encrypt(password_send)
  end

  def self.authenticate(submitted_email, submitted_password)
    user = find_by_email(submitted_email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)  
  end

  private

  	def encrypt_password
      self.salt = make_salt if new_record?
  		self.encrypted_password = encrypt(self.password)
  	end

  	def encrypt(string)
  			secure_hash("#{self.salt}--#{string}")
  	end

    def make_salt
      secure_hash("#{Time.now.utc}--#{self.password}") 
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Accueil"
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "A propos"
  end

  def help
  	@title = "Aide"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Inscription"
  end

  def show
  	@user = User.find(params[:id])
  	@title = @user.nom
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def titre
		base_title = "Mon tutoriel Ruby On Rails"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def gravatar_for(user, options = {:size => 50})
		gravatar_image_tag(user.email.downcase, :alt => user.nom, 
												:class => "gravatar", 
												:gravatar => options)
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>

	<nav>
		<ul>
			<li><%= link_to "A propos", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
	
</footer>

app/views/layouts/_header.html.erb
<header>
		
	<%= image_tag("logo.png", :alt => "Sample App", :class => "round") %>

	<nav class='round'>
		<ul class="nav nav-pills">
			<li><%= link_to "Accueil", root_path %></li>
			<li><%= link_to "Aide", help_path %></li>
			<li><%= link_to "Connexion", '#' %></li>
		</ul>
	</nav>

</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "bootstrap/css/bootstrap.min", :media => "all" %>
<%= stylesheet_link_tag    "styles", :media => "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= titre %></title>
  <%= render "layouts/stylesheets"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		
		<%= render "layouts/header" %>

		<section class="round">
			
			<%= yield %>

		</section>


		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
		
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails Tutorial sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette application exemple, consultez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Application Exemple</h1>
<p>C'est la page d'accueil pour l'application exemple du tutoriel Ruby On Rails</p>

<%= link_to "S'inscrire!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div id="profile">
	
	<div class="main">
		
		<h1>
			<%= gravatar_for @user %>
			<%= @user.nom %>
		</h1>

	</div>

	<aside class="round">
		<ul>
			<li><span>Nom : </span><%= @user.nom %></li>
			<li><span>URL : </span><%= link_to user_path(@user), @user %></li>
		</ul>
	</aside>

</div>

<div class="clear"></div>